services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: salty-spitoon-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/sprint/data
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: team-solid
      MINIO_ROOT_PASSWORD: "@team-solid"
      MINIO_DEFAULT_BUCKETS: images
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 1m
      retries: 5
    volumes:
      - minio_volume:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
  createBucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set salty-spitoon http://minio:9000 salty-spitoon @salty-spitoon &&
      /usr/bin/mc mb salty-spitoon/images
      "

volumes:
  psql_volume_bp:
  minio_volume:
