// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"
)

type Activity struct {
	ID              int64
	UserID          int64
	ActivityType    string
	DoneAt          time.Time
	DurationMinutes int32
	CaloriesBurned  int32
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Name         sql.NullString
	Preference   sql.NullString
	WeightUnit   sql.NullString
	HeightUnit   sql.NullString
	Weight       sql.NullInt32
	Height       sql.NullInt32
	ImageUri     sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
