// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package repository

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
    VALUES ($1, $2)
    RETURNING id
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const patchProfileById = `-- name: PatchProfileById :exec
UPDATE users 
    SET 
        preference = COALESCE($2, preference),
        weight_unit = COALESCE($3, weight_unit),
        height_unit = COALESCE($4, height_unit),
        weight = COALESCE($5, weight),
        height = COALESCE($6, height),
        name = COALESCE($7, name),
        image_uri = COALESCE($8, image_uri)
WHERE id = $1
`

type PatchProfileByIdParams struct {
	ID         int64
	Preference sql.NullString
	WeightUnit sql.NullString
	HeightUnit sql.NullString
	Weight     sql.NullInt32
	Height     sql.NullInt32
	Name       sql.NullString
	ImageUri   sql.NullString
}

func (q *Queries) PatchProfileById(ctx context.Context, arg PatchProfileByIdParams) error {
	_, err := q.db.ExecContext(ctx, patchProfileById,
		arg.ID,
		arg.Preference,
		arg.WeightUnit,
		arg.HeightUnit,
		arg.Weight,
		arg.Height,
		arg.Name,
		arg.ImageUri,
	)
	return err
}

const selectProfileById = `-- name: SelectProfileById :one
SELECT preference, weight_unit as weightUnit, height_unit as heightUnit, weight, height, email, name, image_uri as imageUri FROM users where id = $1
`

type SelectProfileByIdRow struct {
	Preference sql.NullString
	Weightunit sql.NullString
	Heightunit sql.NullString
	Weight     sql.NullInt32
	Height     sql.NullInt32
	Email      string
	Name       sql.NullString
	Imageuri   sql.NullString
}

func (q *Queries) SelectProfileById(ctx context.Context, id int64) (SelectProfileByIdRow, error) {
	row := q.db.QueryRowContext(ctx, selectProfileById, id)
	var i SelectProfileByIdRow
	err := row.Scan(
		&i.Preference,
		&i.Weightunit,
		&i.Heightunit,
		&i.Weight,
		&i.Height,
		&i.Email,
		&i.Name,
		&i.Imageuri,
	)
	return i, err
}

const selectUserByEmail = `-- name: SelectUserByEmail :one
SELECT id, password_hash FROM users where email = $1
`

type SelectUserByEmailRow struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) SelectUserByEmail(ctx context.Context, email string) (SelectUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, selectUserByEmail, email)
	var i SelectUserByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}
